development:
  adapter: postgresql
  encoding: unicode
  database: blabber_development
  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: blabber_test
  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>
  pool: 5
